---
# This executes when the specified action via the variable "esx_power_state"
  - name: Manage ESX host power state
    vmware_host_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ inventory_hostname }}"
      state: "{{ esx_power_state }}"
    delegate_to: localhost

  - name: Wait for ESX host to be available
    local_action:
      module: wait_for
      host: "{{ inventory_hostname }}"
      port: 22
      state: started
      sleep: 30
      timeout: 3600

  # other tasks here
...
